// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Expecto.Hopac")>]
[<assembly: AssemblyProductAttribute("Expecto.Hopac")>]
[<assembly: AssemblyCopyrightAttribute("Copyright © 2018")>]
[<assembly: AssemblyDescriptionAttribute("Advanced testing library for F#")>]
[<assembly: AssemblyVersionAttribute("7.0.0")>]
[<assembly: AssemblyFileVersionAttribute("7.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Expecto.Hopac"
    let [<Literal>] AssemblyProduct = "Expecto.Hopac"
    let [<Literal>] AssemblyCopyright = "Copyright © 2018"
    let [<Literal>] AssemblyDescription = "Advanced testing library for F#"
    let [<Literal>] AssemblyVersion = "7.0.0"
    let [<Literal>] AssemblyFileVersion = "7.0.0"
