// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Expecto")>]
[<assembly: AssemblyProductAttribute("Expecto")>]
[<assembly: AssemblyCopyrightAttribute("Copyright 2018")>]
[<assembly: AssemblyDescriptionAttribute("Advanced testing library for F#")>]
[<assembly: AssemblyVersionAttribute("7.0.1")>]
[<assembly: AssemblyFileVersionAttribute("7.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Expecto"
    let [<Literal>] AssemblyProduct = "Expecto"
    let [<Literal>] AssemblyCopyright = "Copyright 2018"
    let [<Literal>] AssemblyDescription = "Advanced testing library for F#"
    let [<Literal>] AssemblyVersion = "7.0.1"
    let [<Literal>] AssemblyFileVersion = "7.0.1"
