// Auto-Generated by FAKE; do not edit
namespace Expecto.AssemblyInfo
open System.Reflection

[<assembly: AssemblyTitleAttribute("Expecto")>]
[<assembly: AssemblyProductAttribute("Expecto")>]
[<assembly: AssemblyCopyrightAttribute("Copyright 2019")>]
[<assembly: AssemblyDescriptionAttribute("Advanced testing library for F#")>]
[<assembly: AssemblyVersionAttribute("8.9.1")>]
[<assembly: AssemblyFileVersionAttribute("8.9.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Expecto"
    let [<Literal>] AssemblyProduct = "Expecto"
    let [<Literal>] AssemblyCopyright = "Copyright 2019"
    let [<Literal>] AssemblyDescription = "Advanced testing library for F#"
    let [<Literal>] AssemblyVersion = "8.9.1"
    let [<Literal>] AssemblyFileVersion = "8.9.1"
