// Auto-Generated by FAKE; do not edit
namespace Expecto.AssemblyInfo
open System.Reflection

[<assembly: AssemblyTitleAttribute("Expecto")>]
[<assembly: AssemblyProductAttribute("Expecto")>]
[<assembly: AssemblyCopyrightAttribute("Copyright 2018")>]
[<assembly: AssemblyDescriptionAttribute("Advanced testing library for F#")>]
[<assembly: AssemblyVersionAttribute("8.7.0")>]
[<assembly: AssemblyFileVersionAttribute("8.7.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Expecto"
    let [<Literal>] AssemblyProduct = "Expecto"
    let [<Literal>] AssemblyCopyright = "Copyright 2018"
    let [<Literal>] AssemblyDescription = "Advanced testing library for F#"
    let [<Literal>] AssemblyVersion = "8.7.0"
    let [<Literal>] AssemblyFileVersion = "8.7.0"
