// Auto-Generated by FAKE; do not edit
namespace Expecto.AssemblyInfo
open System.Reflection

[<assembly: AssemblyTitleAttribute("Expecto.FsCheck")>]
[<assembly: AssemblyProductAttribute("Expecto.FsCheck")>]
[<assembly: AssemblyCopyrightAttribute("Copyright 2018")>]
[<assembly: AssemblyDescriptionAttribute("Advanced testing library for F#")>]
[<assembly: AssemblyVersionAttribute("8.6.5")>]
[<assembly: AssemblyFileVersionAttribute("8.6.5")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Expecto.FsCheck"
    let [<Literal>] AssemblyProduct = "Expecto.FsCheck"
    let [<Literal>] AssemblyCopyright = "Copyright 2018"
    let [<Literal>] AssemblyDescription = "Advanced testing library for F#"
    let [<Literal>] AssemblyVersion = "8.6.5"
    let [<Literal>] AssemblyFileVersion = "8.6.5"
