// Auto-Generated by FAKE; do not edit
namespace Expecto.AssemblyInfo
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Expecto.FsCheck")>]
[<assembly: AssemblyProductAttribute("Expecto.FsCheck")>]
[<assembly: AssemblyCopyrightAttribute("Copyright 2019")>]
[<assembly: AssemblyDescriptionAttribute("Advanced testing library for F#")>]
[<assembly: AssemblyVersionAttribute("8.11.0")>]
[<assembly: AssemblyFileVersionAttribute("8.11.0")>]
[<assembly: InternalsVisibleToAttribute("Expecto.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Expecto.FsCheck"
    let [<Literal>] AssemblyProduct = "Expecto.FsCheck"
    let [<Literal>] AssemblyCopyright = "Copyright 2019"
    let [<Literal>] AssemblyDescription = "Advanced testing library for F#"
    let [<Literal>] AssemblyVersion = "8.11.0"
    let [<Literal>] AssemblyFileVersion = "8.11.0"
    let [<Literal>] InternalsVisibleTo = "Expecto.Tests"
