// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Expecto.FsCheck")>]
[<assembly: AssemblyProductAttribute("Expecto.FsCheck")>]
[<assembly: AssemblyCopyrightAttribute("Copyright © 2018")>]
[<assembly: AssemblyDescriptionAttribute("Advanced testing library for F#")>]
[<assembly: AssemblyVersionAttribute("5.1.2")>]
[<assembly: AssemblyFileVersionAttribute("5.1.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Expecto.FsCheck"
    let [<Literal>] AssemblyProduct = "Expecto.FsCheck"
    let [<Literal>] AssemblyCopyright = "Copyright © 2018"
    let [<Literal>] AssemblyDescription = "Advanced testing library for F#"
    let [<Literal>] AssemblyVersion = "5.1.2"
    let [<Literal>] AssemblyFileVersion = "5.1.2"
